### ISSUE TITLE
Generate ebook MSTG to PDF

### ISSUE THREAD

**Issue by itsethack** [OWASP/owasp-mstg#1768] opened 2020-06-05 10:33 UTC
**Describe the issue**
Repost on #owasp-community on slack https://owasp.slack.com/archives/C04T40NND/p1591346700196800

Hi, I wanna generate pdf OWASP-MSTG v 1.2 from https://github.com/OWASP/owasp-mstg
I already clone the repo, and do run "./tools/docker/run_docker_mstg_generation_on_local.sh"
but I got error (see the picture).
@jeroenwillemsen was said that script was made for mac os x

So, How to generate to .pdf files on Linux or Windows?

![image](https://user-images.githubusercontent.com/65939746/83866826-9c520800-a752-11ea-9f25-7ee079b796f7.png)

Thanks

**Comment by ThunderSon** [comment] 2020-06-05 10:51
I received no errors whatsoever on Linux.
I believe the issue is with the line endings on Windows, which is CRLF vs LF on linux (and Mac).
You need to amend that on your terminal settings.

**Comment by ThunderSon** [comment] 2020-06-05 10:56
To test that out and confirm this analysis, please do the following and test out:
`sed -i.bak 's/\r$//' ./tools/docker/run_docker_mstg_generation_on_local.sh`

**Comment by itsethack** [comment] 2020-06-05 14:57
Thanks, it works and no error after i test it with that 
> `sed -i.bak 's/\r$//' ./tools/docker/run_docker_mstg_generation_on_local.sh`

But, after i finish the 7/7 step and the script going to Generate Document,
I got another error when running script pandoc_makedocs.sh ,
.( /tools/docker/pandoc_makedocs.sh: line 7: $1: unbound variable )

![image](https://user-images.githubusercontent.com/65939746/83891387-46438b80-a777-11ea-8941-35be4e341875.png)

Any solution?

Thanks

**Comment by commjoen** [comment] 2020-06-05 18:03
maybe run it ` bash -c ./tools/docker/run_docker_mstg_generation_on_local.sh ` ?

**Comment by itsethack** [comment] 2020-06-06 04:06
> maybe run it `bash -c './tools/docker/run_docker_mstg_generation_on_local.sh'` ?

I am sorry @commjoen , there no change, the error still same
![image](https://user-images.githubusercontent.com/65939746/83935651-ca345c80-a7e5-11ea-9c61-7694f924e3d9.png)

**Comment by ThunderSon** [comment] 2020-06-07 09:03
I uploaded an attempt to transform this into Windows executable. Please try it. Replace .txt with .sh and set it in the same folder location.
Your issue is still porting from linux files to windows.

[mstg_generation_win.txt](https://github.com/OWASP/owasp-mstg/files/4741605/mstg_generation_win.txt)

**Comment by itsethack** [comment] 2020-06-07 16:07
> I uploaded an attempt to transform this into Windows executable. Please try it. Replace .txt with .sh and set it in the same folder location.
> Your issue is still porting from linux files to windows.
> 
> [mstg_generation_win.txt](https://github.com/OWASP/owasp-mstg/files/4741605/mstg_generation_win.txt)

I'm sorry, I still got same error,
![image](https://user-images.githubusercontent.com/65939746/83973881-89d2fc80-a913-11ea-8a72-f3072b8db7b7.png)

I used WSL (Ubuntu) on Windows 10 to run the .sh files

**Comment by cpholguera** [comment] 2021-04-07 18:51
Fixed in our new pipeline

**Closed by cpholguera** 2021-04-07 18:51 UTC
Labels: question
