### ISSUE TITLE
differ from MASVS

### ISSUE THREAD

**Issue by Ralireza** [OWASP/owasp-mstg#1722] opened 2020-05-09 10:50 UTC
in the English checklist, the android requirement differs from the MASVS checklist.
I don't know its an issue or not but not good :)

**Comment by commjoen** [comment] 2020-05-09 12:54
This should be fixed in https://github.com/OWASP/owasp-mstg/pull/1708 :) can you verify please ^^?

**Comment by Ralireza** [comment] 2020-05-09 19:03
security requirement android in:
https://github.com/OWASP/owasp-mstg/blob/master/Checklists/Mobile_App_Security_Checklist-English_1.1.2.xlsx

vs 

https://mobile-security.gitbook.io/masvs/security-requirements/0x06-v1-architecture_design_and_threat_modelling_requireme

the gitbook has more

**Comment by commjoen** [comment] 2020-05-09 19:13
Ah no, https://github.com/OWASP/owasp-mstg/blob/master/Checklists/Mobile_App_Security_Checklist-English_1.1.2.xlsx is version 1.1.2, we are currently with the MASVS at version 1.2 (=newer). In #1708 version 1.2 of the MASVS is ported to the Excel. 
So no deletion of gitbook requirements ^^.

**Comment by commjoen** [comment] 2020-05-09 19:14
Closing as duplicate of #1691 .

**Closed by commjoen** 2020-05-09 19:14 UTC
